name: Build and Publish Vote Image

on:
  push:
    branches:
      - main
    paths:
      - 'vote/**'

jobs:
  image-build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Generate Tag
        id: gentag
        run: |
          VERSION=sha-${GITHUB_SHA::8}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF/refs\/tags\//}
          fi
          echo ::set-output name=BUILD_DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=VERSION::${VERSION}
      - name: Kaniko Build and Publish
        uses: aevea/action-kaniko@master
        with:
          image: dopsdemo/vote
          tag: ${{ steps.gentag.outputs.VERSION }}-${{ steps.gentag.outputs.BUILD_DATE }}
          path: ./vote
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          cache: true
          cache_registry: dopsdemo/votecache

